apiVersion: apps/v1
kind: Deployment
metadata:
  name: noip
  labels:
    app: noip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noip
  template:
    metadata:
      labels:
        app: noip
    spec:
      containers:
      - name: noip
        image: gilesknap/noip
        imagePullPolicy: Always
        resources:
          limits:
            memory: "10Mi"
            cpu: "100m"
        env:
        # environment variables from the secret provide creds for noip
        - name: NOIP_USER
          valueFrom:
            secretKeyRef:
              name: noip-credentials
              key: user
        - name: NOIP_PWD
          valueFrom:
            secretKeyRef:
              name: noip-credentials
              key: password
        livenessProbe:
          exec:
            # execute pgrep to make sure noip2 is still running
            command:
            - pgrep
            - noip2
          initialDelaySeconds: 10
          periodSeconds: 5
